<script>
import { sendWsMessage, messages } from '../socket.svelte.js';
import { sessionToken, subscriptionsHistory } from '../state.svelte.js';
import { onMount } from 'svelte';
onMount(() => {
  // every 60 seconds request the subscriptions history
  sendWsMessage('RequestSubscriptionsHistory,' + $sessionToken);
  setInterval(() => {
    sendWsMessage('RequestSubscriptionsHistory,' + $sessionToken);
  }, 60000);
})

let amount = "9.99";
let description = 'Test payment';
let isSatsSelected = false;
let currency = 'EUR';
function sendPayment() {
  // Get the value from the hidden input generated by uk-select
  const frequencyInput = document.querySelector('input[name="frequency-select"]');
  const selectedFrequency = (frequencyInput instanceof HTMLInputElement && frequencyInput.value) ? frequencyInput.value : undefined;

  if (!selectedFrequency) {
    console.error('No frequency selected');
    return;
  }

  if (isSatsSelected) {
    sendWsMessage('RequestRecurringPayment,' + $sessionToken + ',Millisats,' + (amount + '000') + ',' + description + ',' + selectedFrequency);
  } else {
    sendWsMessage('RequestRecurringPayment,' + $sessionToken + ',' + currency + ',' + amount + ',' + description + ',' + selectedFrequency);
  }
}

$: if (!isSatsSelected) {
  if(!amount.includes('.')) {
    amount = amount + '.00';
  }
}

// remove . and 2 digits after the dot from amount if sats is selected
$: if (isSatsSelected) {

  if(amount.includes('.')) {
    amount = amount.slice(0, -3);
  }
}

$: if ($messages.length > 0) {
    let lastMessage = $messages[$messages.length - 1];
    if (lastMessage.cmd === 'SubscriptionsHistory') {
      console.log('SubscriptionsHistory', lastMessage.history);
      subscriptionsHistory.set(lastMessage.history);
    }

  }

</script>

                        <div>
                          <h3 class="text-lg font-medium">Subscription</h3>
                          <p class="text-muted-foreground text-sm">
                            Request a recurring payment.
                          </p>
                        </div>
                        <div class="border-border border-t"></div>
                     
                        <div class="space-y-2">
                          <label class="uk-form-label" for="username">Currency</label>
                          <div class="flex items-center space-x-2">
                            <input
                              class="uk-toggle-switch uk-toggle-switch-primary"
                              id="toggle-switch"
                              type="checkbox"
                              bind:checked={isSatsSelected}
                            />
                            <label class="uk-form-label" for="toggle-switch">Sats</label>
                          </div>
                          {#if !isSatsSelected}
                            <input class="uk-input w-24" type="text" placeholder="EUR" bind:value={currency} />
                          {/if}
                          <div class="uk-form-help text-muted-foreground">
                            Select the currency you want to pay in.
                          </div>
                        </div>

                        <div class="space-y-2">
                          <label class="uk-form-label" for="username">Amount</label>
                          <input
                            class="uk-input"
                            id="amount"
                            type="text"
                            placeholder="100"
                            bind:value={amount}
                          />
                          <div class="uk-form-help text-muted-foreground">
                            Enter the amount you want to pay.
                          </div>
                        </div>
                        <div class="space-y-2">
                          <label class="uk-form-label" for="description"
                            >Description</label
                          >
                          <textarea
                            class="uk-textarea"
                            id="description"
                            placeholder="Test payment"
                            bind:value={description}
                          ></textarea>
                          <div class="uk-form-help text-muted-foreground">
                            Enter a description for the payment.
                          </div>
                        </div>
                        <div class="space-y-2">
                            <label class="uk-form-label block" for="email">Frequency</label>
                            <div class="h-10">
                              <uk-select
                                icon="chevrons-up-down"
                                class="fr-select"
                                cls-custom="button: uk-input-fake justify-between; dropdown: w-full"
                                name="frequency-select"
                                id="frequency"
                                >
                                <select hidden>
                                  <optgroup label="Select a frequency">
                                    <option value="minutely" selected>Minutely</option>
                                    <option value="hourly">Hourly</option>
                                    <option value="daily">Daily</option>
                                    <option value="weekly">Weekly</option>
                                    <option value="monthly">Monthly</option>
                                    <option value="yearly">Yearly</option>
                                  </optgroup>
                                </select>
                              </uk-select>
                            </div>
                            <div class="uk-form-help text-muted-foreground">
                              Select the frequency of the payment.
                            </div>
                        </div>
                        <div class="">
                          <button class="uk-btn uk-btn-primary" on:click={sendPayment}>Send Payment Request</button>
                        </div>
                        

