<script>
import { sendWsMessage, messages } from '../socket.svelte.js';
import { sessionToken, subscriptionsHistory } from '../state.svelte.js';
import { onMount } from 'svelte';

onMount(() => {
  // every 60 seconds request the subscriptions history
  sendWsMessage('RequestSubscriptionsHistory,' + $sessionToken);
  setInterval(() => {
    sendWsMessage('RequestSubscriptionsHistory,' + $sessionToken);
  }, 60000);
})

let amount = "9.99";
let description = 'Test payment';
let isSatsSelected = false;
let currency = 'EUR';
let subscriptionPayments = [];
let modalSubscription = undefined;
let searchQuery = '';

function sendPayment() {
  // Get the value from the hidden input generated by uk-select
  const frequencyInput = document.querySelector('input[name="frequency-select"]');
  const selectedFrequency = (frequencyInput instanceof HTMLInputElement && frequencyInput.value) ? frequencyInput.value : undefined;

  if (!selectedFrequency) {
    console.error('No frequency selected');
    return;
  }

  if (isSatsSelected) {
    sendWsMessage('RequestRecurringPayment,' + $sessionToken + ',Millisats,' + (amount + '000') + ',' + description + ',' + selectedFrequency);
  } else {
    sendWsMessage('RequestRecurringPayment,' + $sessionToken + ',' + currency + ',' + amount + ',' + description + ',' + selectedFrequency);
  }
  // Reset form
  amount = "9.99";
  description = 'Test payment';
  isSatsSelected = false;
  currency = 'EUR';
}

$: if (!isSatsSelected) {
  if(!amount.includes('.')) {
    amount = amount + '.00';
  }
}

// remove . and 2 digits after the dot from amount if sats is selected
$: if (isSatsSelected) {
  if(amount.includes('.')) {
    amount = amount.slice(0, -3);
  }
}

function getSubscriptionPayments(subscription) {
  modalSubscription = subscription;
  sendWsMessage('GetSubscriptionPayments,' + $sessionToken + ',' + subscription.portalSubscriptionId);
}

function cancelSubscription(subscriptionId) {
  // sendWsMessage('CancelSubscription,' + $sessionToken + ',' + subscriptionId);
  alert('Not implemented yet');
}

function formatPaymentStatus(payment) {
  if (payment.paid === undefined || payment.paid === null) {
    return 'Pending';
  }
  return payment.paid ? 'Paid' : 'Not Paid';
}

function formatPaymentStatusClass(payment) {
  if (payment.paid === undefined || payment.paid === null) {
    return '';
  }
  return payment.paid ? 'uk-badge-secondary' : 'uk-badge-destructive';
}

// Filter subscriptions based on search query
$: filteredSubscriptions = ($subscriptionsHistory || []).filter(subscription => {
  if (!searchQuery.trim()) return true;
  const query = searchQuery.toLowerCase();
  const currencyStr = (subscription.currency === 'Millisats' ? 'Sats' : subscription.currency).toLowerCase();
  const amountStr = String(subscription.currency === 'Millisats' ? subscription.amount / 1000 : subscription.amount / 100).toLowerCase();
  const frequencyStr = subscription.frequency?.toLowerCase() || '';
  const statusStr = subscription.status?.toLowerCase() || '';
  
  return currencyStr.includes(query) ||
         amountStr.includes(query) ||
         frequencyStr.includes(query) ||
         statusStr.includes(query);
});

$: if ($messages.length > 0) {
  let lastMessage = $messages[$messages.length - 1];
  if (lastMessage.cmd === 'SubscriptionsHistory') {
    console.log('SubscriptionsHistory', lastMessage.history);
    subscriptionsHistory.set(lastMessage.history);
  }
  if (lastMessage.cmd === 'SubscriptionPayments') {
    console.log('SubscriptionPayments', lastMessage.history);
    subscriptionPayments = lastMessage.history;
  }
}
</script>

<div class="space-y-6">
  <div>
    <h3 class="text-lg font-medium">Subscription</h3>
    <p class="text-muted-foreground text-sm">
      Manage your subscription requests and history.
    </p>
  </div>
  <div class="border-border border-t"></div>

  <!-- Action bar with search, filter, and button -->
  <div class="flex items-center gap-3 mb-4">
    <div class="flex-1">
      <div class="uk-inline w-full">
        <span class="uk-form-icon">
          <uk-icon icon="search"></uk-icon>
        </span>
        <input
          class="uk-input w-full"
          type="text"
          placeholder="Search..."
          aria-label="Search subscriptions"
          bind:value={searchQuery}
        />
      </div>
    </div>
    <button
      class="uk-btn uk-btn-primary"
      type="button"
      data-uk-toggle="target: #subscription-modal"
    >
      <uk-icon icon="plus" class="mr-2"></uk-icon>
      Send Subscription
    </button>
  </div>

  <!-- Subscription History Table -->
  <div class="overflow-x-auto">
    <table class="uk-table uk-table-divider uk-table-small">
      <thead>
        <tr>
          <th>Currency</th>
          <th>Amount</th>
          <th>Frequency</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {#each filteredSubscriptions as subscription}
        <tr>
          <td>
            <span class="uk-badge uk-badge-default">
              {subscription.currency === 'Millisats' ? 'Sats' : subscription.currency}
            </span>
          </td>
          <td>{subscription.currency === 'Millisats' ? subscription.amount / 1000 : subscription.amount / 100}</td>
          <td>{subscription.frequency.toLowerCase()}</td>
          <td>
            <span class="uk-badge">{subscription.status.toLowerCase()}</span>
          </td>
          <td>
            <div class="flex gap-x-2">
              <button
                class="uk-btn uk-btn-default uk-btn-icon"
                type="button"
                data-uk-toggle="target: #modal-close-default"
                on:click={() => getSubscriptionPayments(subscription)}
              >
                <uk-icon icon="eye"></uk-icon>
              </button>
              {#if subscription.status === 'ACTIVE'}
                <button class="uk-btn uk-btn-default uk-btn-icon" on:click={() => cancelSubscription(subscription.id)}>
                  <uk-icon icon="trash"></uk-icon>
                </button>
              {/if}
            </div>                                  
          </td>
        </tr>
        {/each}
      </tbody>
    </table>
  </div>

  {#if filteredSubscriptions.length > 0}
    <div class="text-sm text-muted-foreground mt-2">
      Page 1-{filteredSubscriptions.length} of {filteredSubscriptions.length} subscriptions - {($subscriptionsHistory || []).length} items
    </div>
  {/if}
</div>

<!-- Subscription Modal -->
<div id="subscription-modal" class="uk-modal-container" data-uk-modal>
  <div class="uk-modal-dialog uk-modal-body">
    <button
      class="uk-modal-close absolute right-4 top-4"
      type="button"
      data-uk-close
      aria-label="Close modal"
    ></button>
    <h2 class="uk-modal-title">Send Subscription Request</h2>
    <p class="text-muted-foreground text-sm mt-2">
      Request a recurring payment.
    </p>
    <div class="border-border border-t mt-4 mb-4"></div>

    <div class="space-y-4">
      <div class="space-y-2">
        <label class="uk-form-label" for="modal-currency">Currency</label>
        <div class="flex items-center space-x-2">
          <input
            class="uk-toggle-switch uk-toggle-switch-primary"
            id="modal-toggle-switch"
            type="checkbox"
            bind:checked={isSatsSelected}
          />
          <label class="uk-form-label" for="modal-toggle-switch">Sats</label>
        </div>
        {#if !isSatsSelected}
          <input class="uk-input w-24" type="text" placeholder="EUR" bind:value={currency} />
        {/if}
        <div class="uk-form-help text-muted-foreground">
          Select the currency you want to pay in.
        </div>
      </div>

      <div class="space-y-2">
        <label class="uk-form-label" for="modal-amount">Amount</label>
        <input
          class="uk-input"
          id="modal-amount"
          type="text"
          placeholder="100"
          bind:value={amount}
        />
        <div class="uk-form-help text-muted-foreground">
          Enter the amount you want to pay.
        </div>
      </div>

      <div class="space-y-2">
        <label class="uk-form-label" for="modal-description">Description</label>
        <textarea
          class="uk-textarea"
          id="modal-description"
          placeholder="Test payment"
          bind:value={description}
        ></textarea>
        <div class="uk-form-help text-muted-foreground">
          Enter a description for the payment.
        </div>
      </div>

      <div class="space-y-2">
        <label class="uk-form-label block" for="modal-frequency">Frequency</label>
        <div class="h-10">
          <uk-select
            icon="chevrons-up-down"
            class="fr-select"
            cls-custom="button: uk-input-fake justify-between; dropdown: w-full"
            name="frequency-select"
            id="modal-frequency"
          >
            <select hidden>
              <optgroup label="Select a frequency">
                <option value="minutely" selected>Minutely</option>
                <option value="hourly">Hourly</option>
                <option value="daily">Daily</option>
                <option value="weekly">Weekly</option>
                <option value="monthly">Monthly</option>
                <option value="yearly">Yearly</option>
              </optgroup>
            </select>
          </uk-select>
        </div>
        <div class="uk-form-help text-muted-foreground">
          Select the frequency of the payment.
        </div>
      </div>

      <div class="flex justify-end gap-2 mt-6">
        <button
          class="uk-modal-close uk-btn uk-btn-default"
          type="button"
        >
          Cancel
        </button>
        <button
          class="uk-modal-close uk-btn uk-btn-primary"
          type="button"
          on:click={sendPayment}
        >
          Send Payment Request
        </button>
      </div>
    </div>
  </div>
</div>

<!-- This is the modal with the default close button -->
<div id="modal-close-default" class="uk-modal-container" data-uk-modal>
  <div class="uk-modal-dialog uk-modal-body">
    <button
      class="uk-modal-close absolute right-4 top-4"
      type="button"
      data-uk-close
      aria-label="Close modal"
    ></button>
    <h2 class="uk-modal-title">Subscription Overview</h2>
    <p class="mt-4">
      This is a list of payments for the subscription <code class="uk-codespan">{modalSubscription?.id}</code>.
      <br>
      Portal Subscription ID: <code class="uk-codespan">{modalSubscription?.portalSubscriptionId}</code>.
    </p>
    <div class="border-border border-t mt-4 mb-4"></div>
    <h3 class="text-lg font-medium">Subscription Payments</h3>
    <table class="uk-table uk-table-divider">
      <thead>
        <tr>
          <th>Currency</th>
          <th>Amount</th>
          <th>Description</th>
          <th>Status</th>
          <th>Created At</th>
        </tr>
      </thead>
      <tbody>
        {#each subscriptionPayments as payment}
          <tr>
            <td>{payment.currency === 'Millisats' ? 'Sats' : payment.currency}</td>
            <td>{payment.currency === 'Millisats' ? payment.amount / 1000 : payment.amount / 100}</td>
            <td>{payment.description}</td>
            <td><span class="uk-badge {formatPaymentStatusClass(payment)}">{formatPaymentStatus(payment)}</span></td>
            <td>{payment.createdAt}</td>
          </tr>
        {/each}
      </tbody>
    </table>
  </div>
</div>

